version: "3.8"

services:
  api:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: neu_backend
    command: "uvicorn main:app --workers=1 --host 0.0.0.0 --port 8000 --reload"
    ports:
      - 8000:8000
    expose:
      - 8000
    env_file: .env
    volumes:
      - ./:/app/server/
    networks:
      - neu-backend-tier

networks:
  neu-backend-tier:
    driver: bridge
